version: "3"
services:
  app:
    build: .
    tty: true
    command: node /app/split-zip-image-to-half.js "/input/資組.zip"
    volumes: 
      - ./app:/app/
      - ./cache:/cache/
      - /tmp/tmp.today/20230106-1656/:/input/