version: "3"
services:
  app:
    image: pudding/docker-app:docker-app-archive-7-zip_app-20231111.162444
    tty: true
    command: node /app/index.js "/input/__INPUT__"
    environment:
      - CONTAINER_NAME=docker-app-archive-7-zip_app
      - LOCAL_VOLUMN_PATH=/input/
      - RUN_COMMAND=ls -la /app/
    volumes: 
      - ./app:/app/
      - ./cache:/cache/
      - __SOURCE__:/input/